### PR TITLE
harp - Unauthorised File Access - Fix:

### PR DESCRIPTION
**Pull request by JamieSlome**
https://github.com/mufeedvh fixed the vulnerability associated with Unauthorised File Access.
This fix is being submitted on behalf of https://github.com/mufeedvh - they have been awarded $25 for fixing the vulnerability through the huntr bug bounty program.

Think you could fix a vulnerability like this - get involved (https://huntr.dev).

Q | A
Version Affected | ALL
Bug Fix | YES
Further References | https://github.com/418sec/harp/pull/3

### CODE REVIEW

**Comment by sintaxi** [comment]
Thanks for the PR. I could you a bit more information. How is the file access unauthorized if there is a symlink in the project directory pointing to it? Why wouldn't we expect this file to be served?

**Comment by JamieSlome** [comment]
@sintaxi - thank you for your response!

The point is that if a symlink was accidentally created, which linked to a sensitive file, this would expose the contents and result in accidental disclosure. If it was intentional disclosure, the user might just put the file directly in the web server's directory, rather than symlink'ing to it?

When a symlink in the project's base directory points to a file outside of the directory, the attacker can access sensitive files on the server, e.g. /etc/passwd...

**Comment by toufik-airane** [comment]
## What exactly is a symlink vulnerability?
Symlink bugs are vulnerabilities that may allow a malicious user to overwrite or read certain or even arbitrary files with the permissions of the invoking user of the vulnerable application or script.

**Comment by JamieSlome** [comment]
@sintaxi - any thoughts on the information provided above?

**Comment by Adar-Checkmarx** [comment]
Hi @sintaxi,
I came across this discussion as part of a security research concerning this vulnerability, do you have any plans to merge this fix in harp?
Please let me know. Thank you

**Pull request merged**
