### PR TITLE
Update to Terraform v1.0.0

### PR DESCRIPTION
**Pull request by kennethormandy**
Terraform v1.0.0 isn’t tagged, and therefore the update isn’t actually committed yet. To run the tests, checkout this branch and then run:

```sh
npm install --save sintaxi/terraform#release-v1.0.0
```

We still have two failing tests, which might be coming from the `_data.js` update, or from how globals are handled in the latest version of Jade, which we updated to.

```sh
  88 passing (12s)
  2 failing

  1) basic should have global vars:
     SyntaxError: /Users/Kenneth/Sites/sintaxi/harp/test/out/basic/globals.json: Unexpected token <
    at Object.parse (native)
    at Object.Module._extensions..json (module.js:450:27)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Context.<anonymous> (/Users/Kenneth/Sites/sintaxi/harp/test/basic.js:27:25)
    at Test.Runnable.run (/Users/Kenneth/Sites/sintaxi/harp/node_modules/mocha/lib/runnable.js:217:15)
    at Runner.runTest (/Users/Kenneth/Sites/sintaxi/harp/node_modules/mocha/lib/runner.js:373:10)
    at /Users/Kenneth/Sites/sintaxi/harp/node_modules/mocha/lib/runner.js:451:12
    at next (/Users/Kenneth/Sites/sintaxi/harp/node_modules/mocha/lib/runner.js:298:14)
    at /Users/Kenneth/Sites/sintaxi/harp/node_modules/mocha/lib/runner.js:308:7
    at next (/Users/Kenneth/Sites/sintaxi/harp/node_modules/mocha/lib/runner.js:246:23)
    at Immediate._onImmediate (/Users/Kenneth/Sites/sintaxi/harp/node_modules/mocha/lib/runner.js:275:5)
    at processImmediate [as _immediateCallback] (timers.js:383:17)


  2) basic should have current vars:
     SyntaxError: /Users/Kenneth/Sites/sintaxi/harp/test/out/basic/current.json: Unexpected token <
    at Object.parse (native)
    at Object.Module._extensions..json (module.js:450:27)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Context.<anonymous> (/Users/Kenneth/Sites/sintaxi/harp/test/basic.js:40:25)
    at Test.Runnable.run (/Users/Kenneth/Sites/sintaxi/harp/node_modules/mocha/lib/runnable.js:217:15)
    at Runner.runTest (/Users/Kenneth/Sites/sintaxi/harp/node_modules/mocha/lib/runner.js:373:10)
    at /Users/Kenneth/Sites/sintaxi/harp/node_modules/mocha/lib/runner.js:451:12
    at next (/Users/Kenneth/Sites/sintaxi/harp/node_modules/mocha/lib/runner.js:298:14)
    at /Users/Kenneth/Sites/sintaxi/harp/node_modules/mocha/lib/runner.js:308:7
    at next (/Users/Kenneth/Sites/sintaxi/harp/node_modules/mocha/lib/runner.js:246:23)
    at Immediate._onImmediate (/Users/Kenneth/Sites/sintaxi/harp/node_modules/mocha/lib/runner.js:275:5)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

### CODE REVIEW

**Comment by davidreher** [comment]
:+1:

**Comment by almirfilho** [comment]
Any update on this? Terraform 1.0.0 was released a while ago.

**Comment by davidreher** [comment]
I think you missed the version bump in the package.json

**Comment by chharvey** [comment]
@davidreher can you submit a pull request fixing that minor change? (`0.13.2` -> `1.0.0`)
Maybe they could release a quick patch or something.

**Comment by chalin** [comment]
@kennethormandy : I have a new feature for https://github.com/angular/angular.io  (Dart API pages) that is blocked, waiting for support for dots in URLs (#531). Any idea when this PR will make its way into an official release?

/cc: @naomiblack @kwalrath

**Comment by sintaxi** [comment]
hey, just seeing this now. Ill get a new release of harp cut with this in it.

**Comment by chalin** [comment]
@sintaxi : thanks for moving this forward. Any idea on when we can expect a release -- FMI? Btw, here's the relevant (sub-)task issue tracker: https://github.com/angular/angular.io/issues/1880.

**Comment by sintaxi** [comment]
Am I the only one getting a failing test on this branch?

```
  89 passing (11s)
  1 failing

  1) headers should be correct with a valid JS file:

      Uncaught AssertionError: expected 404 to equal 200
      + expected - actual

      +200
      -404
```

**Comment by sintaxi** [comment]
@davidreher ah, now I see. thanks.

**Comment by sintaxi** [comment]
I've updated to terraform v1.0.0 and Im still seeing failing tests. Does anyone know if there is still work to do or should this be ready to go?

**Comment by sintaxi** [comment]
I need more info. Is this release expected to be ready or are people waiting on me to add these features? The tests that are failing in January are still failing for me.

**Comment by davidreher** [comment]
I am already using `"harp": "sintaxi/harp.git#3c283617c2fb89ee1e1f7f497511571def0ace34"` in my package.json (which is 0.21) since I am in despereate need for this ...

**Comment by davidreher** [comment]
we can also continue the discussion in #570 since this is exactly the version I am using ...

**Comment by chalin** [comment]
@davidreher : thanks for the reminder that I can pickup a specific commit from github. Unfortunately, that version reports an error when serving parts of angular.io, whereas 0.20.3 (with a manually patched terraform), doesn't. The error I get with 0.21-pre is:
```
Unexpected token: operator (>)
```
@sintaxi : you asked
> I need more info. Is this release expected to be ready or are people waiting on me to add these features? The tests that are failing in January are still failing for me.

What we need for angular.io is a version of harp that is dependent on a version of terraform that supports dots in `current`. I'll continue this discussion in #250, since that is the problem raised there.

**Pull request merged**
